sudo: required

language: javascript

services:
  - docker

before_install:
  - docker build -t bootcamperscollective/bc-webapp-webapi .
  - docker run -d bootcamperscollective/bc-webapp-webapi /bin/sh -c "cd /root/bc-webapp-webapi; npm start;"
  - docker ps -a

script:
  - npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push bootcamperscollective/bc-webapp-webapi;
    fi